name: Production

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout üõéÔ∏è
        uses: actions/checkout@v4

      - name: Setup Node.js 22.21.1
        uses: actions/setup-node@v4
        with:
          node-version: '22.21.1'
          cache: 'npm'

      # Build
      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Build
        run: npm run build

      - name: Deploy build
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: production
          folder: build
          target-folder: build
          clean: true

      - name: Deploy source
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: production
          folder: .
          target-folder: source
          clean: false
